package br.com.cleandomain.entities.repository;

public interface IEducationLevel {

    String INCOMPLETE_ELEMENTARY = "INCOMPLETE ELEMENTARY";

    String COMPLETE_ELEMENTARY = "COMPLETE ELEMENTARY";

    String INCOMPLETE_HIGH = "INCOMPLETE HIGH";

    String COMPLETE_HIGH = "COMPLETE HIGH";

    String INCOMPLETE_HIGHER = "INCOMPLETE_HIGHER";

    String COMPLETE_HIGHER = "COMPLETE_HIGHER";

    String INCOMPLETE_UNDERGRAD = "INCOMPLETE UNDERGRAD";

    String COMPLETE_UNDERGRAD = "COMPLETE UNDERGRAD";

    String INCOMPLETE_GRAD = "INCOMPLETE GRAD";

    String COMPLETE_GRAD = "COMPLETE GRAD";

    String INCOMPLETE_POSTGRAD = "INCOMPLETE POSTGRAD";

    String COMPLETE_POSTGRAD = "COMPLETE POSTGRAD";

    String INCOMPLETE_DOCTORATE = "INCOMPLETE DOCTORATE";

    String COMPLETE_DOCTORATE = "COMPLETE DOCTORATE";

}
